FROM node:16-alpine
WORKDIR '/app'
COPY ./package.json ./
RUN npm install
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache
RUN chmod +x node_modules/.bin/react-scripts
RUN npx update-browserslist-db@latest
COPY ./ ./
CMD ["npm","run","start"]